### ISSUE TITLE
Automatic new tags are added 

### ISSUE THREAD

**Issue by rabingaire** [Hyfer-Tech/TWB#14]
The code works fine when I select single tag. It also works when I select multiple tags but the problem is when I select multiple tags new tags with the selected tags_id is added. For Example 1,6,3.

**Comment by takehiromouri** [comment]
@rabingaire It seems to be working - where is the bug exactly? :)

**Comment by takehiromouri** [comment]
It's working beautifully by the way, great job 👍

**Comment by rabingaire** [comment]
oh! after adding multiple tags look at the dropdown menu you can see new tags added and they are numbers.

**Comment by takehiromouri** [comment]
Ohh OK gotcha, you can fix it like this:

```
<%= f.input :tag_list,
                  collection: ActsAsTaggableOn::Tag.all,
                  input_html: { class: 'chosen-select', multiple: true }
      %>
```

change this to:

```
<%= f.input :tag_list,
                  collection: ActsAsTaggableOn::Tag.all.map(&:name),
                  input_html: { class: 'chosen-select', multiple: true }
      %>
```

**Comment by takehiromouri** [comment]
Basically the problem was that it was sending the tag_ids to the server, when it should have been sending the name of the tag :)
